In [1]:
import pandas as pd

df = pd.read_csv("../data/raw/zomato_dataset.csv")
print(f"Rows    : {len(df):,}")
print(f"Columns : {len(df.columns)}")
df.head()

Rows    : 123,657
Columns : 12

,Restaurant Name,Dining Rating,Delivery Rating,Dining Votes,Delivery Votes,Cuisine,Place Name,City,Item Name,Best Seller,Votes,Prices
0,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Platter Kebab Combo,BESTSELLER,84,249.0
1,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Rumali Shawarma,BESTSELLER,45,129.0
2,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Tandoori Salad,NaN,39,189.0
3,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken BBQ Salad,BESTSELLER,43,189.0
4,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Special Doner Wrap Combo,MUST TRY,31,205.0

In [2]:
df.columns.tolist()

['Restaurant Name',
 'Dining Rating',
 'Delivery Rating',
 'Dining Votes',
 'Delivery Votes',
 'Cuisine ',
 'Place Name',
 'City',
 'Item Name',
 'Best Seller',
 'Votes',
 'Prices']

In [3]:
df.isnull().sum()

Restaurant Name        0
Dining Rating      32236
Delivery Rating     1280
Dining Votes           0
Delivery Votes         0
Cuisine                0
Place Name             0
City                   0
Item Name              0
Best Seller        95715
Votes                  0
Prices                 0
dtype: int64

In [4]:
df["City"].value_counts()

City
Hyderabad       15613
Jaipur          14438
Mumbai          13535
Chennai         13100
Bangalore       12040
Ahmedabad       10178
Kolkata          8662
Pune             8067
Kochi            7759
Raipur           7700
Lucknow          6455
New Delhi        3490
Goa              2360
Banaswadi          97
Ulsoor             66
Magrath Road       54
Malleshwaram       43
Name: count, dtype: int64

In [5]:
df[["Dining Rating", "Delivery Rating"]].describe()

       Dining Rating  Delivery Rating
count   91421.000000    122377.000000
mean        3.822264         3.963184
std         0.408693         0.245900
min         2.500000         2.500000
25%         3.600000         3.800000
50%         3.900000         4.000000
75%         4.100000         4.100000
max         4.800000         4.600000

In [6]:
assert len(df) >= 10_000
assert len(df.columns) >= 8
print(f"Rows: {len(df):,} | Columns: {len(df.columns)} | Cities: {df['City'].nunique()}")
print("Dataset is suitable for the project.")

Rows: 123,657 | Columns: 12 | Cities: 17
Dataset is suitable for the project.